### ISSUE TITLE
<b> font-weight inherits from parent

### ISSUE THREAD

**Issue by richtier** [uktrade/dit-pattern-library#3]
This results in `<b>` not performing how we expect (we expect it to make the text bold to differentiate it from the parent).

The reason this problem happens is we have [this](https://github.com/uktrade/dit-pattern-library/blob/f334d8b264f85d18d82a2234dea538e01662c22f/scss/utilities/_reset.scss#L6) (`font: inherit` implies `font-weight: inherit`, which is undesirable here because it implicitly set the font weight of the `<b>` to it's parent's `font-weight`).

I'm not sure the motives of that class, but I think it can be fixed by changing `font: inherit;` to `font-family: inherit;`

**Comment by richtier** [comment]
It is also possible to replace `<b>` with `<strong>` to work around the issue, but this can be a gotcha for other devs.

**Comment by dahfool** [comment]
@richtier I am following the GDS patterns on this one http://govuk-elements.herokuapp.com/typography/, check the "Legal text" section. The use <strong> rather than <b>.

Only the header and footer should be implement the rest typography, forms.... are not ready.

**Comment by richtier** [comment]
@dahfool great, will use `<strong>` instead of `<b>`.
