### ISSUE TITLE
The 'all' menu does not work without javascript

### ISSUE THREAD

**Issue by richtier** [uktrade/dit-pattern-library#4]
I suggest to make the 'all' menu work for users that that don't have javascript enabled we have the menu as expanded by default, and close it if js is enabled, by including this in the base 
```
<script>document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');</script>
```
and in the css doing
```
<!- hide if js is enabled->
body.js-enabled .navigation-toggle{
    display: none;
}
<!- show if js is disabled (absence of js-enabled class ->
body .navigation-toggle{
    display: inline-block;
}
```

**Comment by dahfool** [comment]
@richtier Please feel free to implement.

**Comment by richtier** [comment]
cool. perhaps `<style>` tag inside a `<noscript>` tag would be neater than the solution I proposed.

**Comment by dahfool** [comment]
@richtier I think the menu could be open without javascript 

````
<div class="navigation-toggle background--dark-navy navigation-toggle--open">
````

If we have javascript we remove the navigation-toggle--open class

**Comment by richtier** [comment]
Fixed in the linked PR.
