### ISSUE TITLE
IE8 Grid support for Bourbon Neat

### ISSUE THREAD

**Issue by stevenburnell-dit** [uktrade/dit-pattern-library#5]
Essentially, this...

`.col-6 { @include span-columns(6); }`

...will produce something like this:

```
.col-6 {
  float: left;
  display: block;
  margin-right: 1.53846%;
  width: 49.23077%; 
}

.col-6:last-child {
    margin-right: 0; 
}
```

This will not work in IE8 due to lack of :last-child support. 
For this to work in IE8, we'd probably want to produce something like this (untested code example), altering the margin and pseudo class:

```
.col-6 {
  float: left;
  display: block;
  margin-left: 1.53846%;
  width: 49.23077%; 
}

.col-6:first-child {
    margin-left: 0; 
}
```

Problem here is, after inspecting the related code directly (node_modules/bourbon-neat/app/assets/stylesheets/grid/_span-columns.scss), it seems that Bourbon Neat does not appear to offer a way to change this.

**Comment by richtier** [comment]
perhaps use a [`last-child` polyfill](http://selectivizr.com/). advantage is it will just work. disadvantage is it requires js.

**Comment by dahfool** [comment]
@richtier @stevenburnell-dit 
https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices

I don't think we need polyfill, we could use conditional stylesheet to make it functional in IE8.

**Comment by dahfool** [comment]
@richtier @stevenburnell-dit i have pushed some changes to fix images on ie8.

**Comment by stevenburnell-dit** [comment]
Possible solutions:

1). Use an alternative to Bourbon Neat that supports IE8
2). Apply extra functionality to sass files that might produce a custom IE8 stylesheet without altering what is currently in place (e.g. something akin to writing an alternative to span-columns, which is the currently problem for IE8 first-child/last-child grid issues).
3). Add JS-only fix using selectivizr (selectivizr.com - this also requires a compatible JS library to work, e.g. jQuery or Mootools)
4). Manually alter the compiled CSS output and save as an IE8.css file (e.g. rewrite the :last-child selectors to :first-child, etc). 

Options 1, 2, and 4 are obviously better by not involving JS. 
Option 2 or 4 would be best for least amount of rework effort.
Option 3 and 4 are easiest but option 4 would need reworking if ever the base CSS changes. 


For the sake of time-saving, a (temporary) solution choice of JS-only (3), will be put in place. I am told, since the current development process is to cut-and-paste, rather than inherit, code solutions, others will be free to make an alternative choice on their own projects - this is especially important for preferred supporting JS library choice. 

Expect that any better solution (1 or 2) will be added if effort is taken to fix properly at some point.

**Comment by dahfool** [comment]
@stevenburnell-dit @richtier i will close this issue
